name: Messaging
version: '${project.version}'
main: world.ntdi.messaging.Messaging
api-version: 1.19
commands:
  msg:
    usage: "/msg <player> <message>"
    aliases:
      - message
      - send
      - w
      - r
